version: 2

sources:
  - name: raw
    schema: gz_raw_data  # This is the dataset name in BigQuery
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: Raw sales data
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: foreign key to ship
          - name: pdt_id
            description: foreign key to product
          - name: revenue
            description: revenue = quantity * selling price
          - name: quantity
            description: quantity of purchased products for this order
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
      - name: product
        identifier: raw_gz_product
        description: Raw product data
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: purchase_price
            description: purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: Raw shipment data
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: price for shipment of this order
          - name: log_cost
            description: cost of preparing the parcel in the warehouse
          - name: ship_cost
            description: the shipping cost paid to the carrier/transporter
      - name: adwords
        identifier: raw_gz_adwords
        columns:
          - name: date_date
            description: date when the campaign data was recorded 
          - name: paid_source
            description: the advertising platform or source from which the paid campaign originated 
          - name: campaign_key
            description: a unique identifier for the campaign
          - name: camPGN_name
            description: the name of the campaign, detailing its specific focus or target
          - name: ads_cost
            description: total cost incurred for advertisements on that specific date
          - name: impression
            description: number of times the advertisement was displayed or seen by users
          - name: click
            description: number of times users clicked on the advertisement
      - name: bing
        identifier: raw_gz_bing
        columns:
          - name: date_date
            description: date when the campaign data was recorded 
          - name: paid_source
            description: the advertising platform or source from which the paid campaign originated 
          - name: campaign_key
            description: a unique identifier for the campaign
          - name: camPGN_name
            description: the name of the campaign, detailing its specific focus or target
          - name: ads_cost
            description: total cost incurred for advertisements on that specific date
          - name: impression
            description: number of times the advertisement was displayed or seen by users
          - name: click
            description: number of times users clicked on the advertisement  
      - name: criteo
        identifier: raw_gz_criteo
        columns:
          - name: date_date
            description: date when the campaign data was recorded 
          - name: paid_source
            description: the advertising platform or source from which the paid campaign originated 
          - name: campaign_key
            description: a unique identifier for the campaign
          - name: camPGN_name
            description: the name of the campaign, detailing its specific focus or target
          - name: ads_cost
            description: total cost incurred for advertisements on that specific date
          - name: impression
            description: number of times the advertisement was displayed or seen by users
          - name: click
            description: number of times users clicked on the advertisement
      - name: facebook
        identifier: raw_gz_facebook
        columns:
          - name: date_date
            description: date when the campaign data was recorded 
          - name: paid_source
            description: the advertising platform or source from which the paid campaign originated 
          - name: campaign_key
            description: a unique identifier for the campaign
          - name: camPGN_name
            description: the name of the campaign, detailing its specific focus or target
          - name: ads_cost
            description: total cost incurred for advertisements on that specific date
          - name: impression
            description: number of times the advertisement was displayed or seen by users
          - name: click
            description: number of times users clicked on the advertisement

models:
  - name: int_campaigns
    description: data from all campaigns
    tests:
      - unique:
          column_name: "(campaign_key || '-' || date_date)"
    
